# These are supported funding model platforms

github: [rafaelsabino]
tidelift: npm/SqLiteInstall
community_bridge: cloud-foundry
liberapay: Single-Liberapay-SQLITE
custom: ['alliancetechsystem.com']
